### ISSUE TITLE
unknown keyword: :tracer

### ISSUE THREAD

**Issue by onyx-and-iris** [hanazuki/ruby-obs-websocket#3]
Hello. Thank you for creating this library, it's awesome!

When using the files from rubygems I get error:

`initialize': unknown keyword: :tracer (ArgumentError)
        from ./main.rb:16:in `new'
        from ./main.rb:16:in `run'
        from ./main.rb:104:in `<main>'

In websocket.rb def initialize(websocket, executor: :io, tracer: nil) was missing tracer.

Regards.

**Comment by hanazuki** [comment]
I guess you are trying the example from `master` branch, which I recently updated with v5 protocol support and several feature additions. That version of the library is not yet uploaded to the RubyGems.org repository, as it needs further testing in applications.

You can try the prerelease version by instructing Bundler to fetch the gem from GitHub:
```ruby
# In your Gemfile
gem 'obs-websocket', git: 'https://github.com/hanazuki/obs-websocket'
```
I would appreciate it if you could report any troubles you encounter with the development version in this issue tracker.

Also, please be aware that this product is not yet stabilized (it's version 0!) and subject to breaking interface changes.

**Comment by onyx-and-iris** [comment]
Thank you for the quick response. If I encounter any issues I will make sure I report them. I will close this as resolved for now.
